### ISSUE TITLE
Default gui textbutton background file missing on phone

### ISSUE THREAD

**Issue by fk1995** [renpy/rapt#16]
If I copy choice_idle_background.png and choice_hover_background.png from gui/button to gui/phone/button manually, this got fixed.

This problem can be reproduced by creating a new project, insert a menu and simulate it on Android mode on PC or build it as an apk and run it on any device.

**Comment by btrdurfee** [comment]
Should this be in the "rapt" project, or in the "renpy" project?

Either way, I can validate that this is indeed an issue and is not exclusive to Android. It happens on iOS as well.
