### ISSUE TITLE
target_version set to 14, should be higher before August 2018

### ISSUE THREAD

**Issue by jmfergeau** [renpy/rapt#18]
After the 1st of august 2018, apps in Google Play will require apps to target API level at 26 at least, because of Android 8.0. [More details here](https://developer.android.com/distribute/best-practices/develop/target-sdk).

I'm not sure if it's only my game or if it does it for any game, but when I compile it with rapt, the target version is set to 14. Which gives me a warning on the Google Play apps publishing saying that I won't be able to post new games after august 2018 or updates after november 2018.

Since we're june 2018 and that I haven't seen a word about that around here, thought it would be nice to think about it. ^^

EDIT: Seen Renpytom speaking about it recently on Twitter. I guess the fix is on the way. ^^

**Comment by Teashrock** [comment]
Not whole world does have Android 8.0 or 9.0. Android 7 is widespreading now, but there a lot of those who has Android 6, 5 or even 4. Maybe it'll be better to allow a choice between targeting builds (with a warning about Google Play)?

**Comment by renpytom** [comment]
This has been fixed as of Ren'Py 7.1.
