### ISSUE TITLE
self.android.check_pause() craches android game

### ISSUE THREAD

**Issue by dmalves** [renpy/rapt#2]
when I use self.android.check_pause() to check if the game is paused on android the app just crash.

is this function still in use?

if I compare with https://github.com/renpytom/rapt-pygame-example/blob/master/main.py

it looks like pause is not used anymore? Cloud you please help me understant how to handle android app life cicle in rapt. I am using the latest buid:
renpy-nightly-2015-12-20-b4e67cd-rapt.zip

**Comment by renpytom** [comment]
It's not. The relevant code is:

https://github.com/renpytom/rapt-pygame-example/blob/master/main.py#L81

and 

https://github.com/renpytom/rapt-pygame-example/blob/master/main.py#L90

which are events generated before suspend and after resume, respectively. Handle those and you should be good.
