### ISSUE TITLE
Build universal (multi-ABI/multi-arch) APK

### ISSUE THREAD

**Issue by Beuc** [renpy/rapt#28]
Ren'Py is now building 3 different .apk for the arm, arm64 and x86_64 architectures.
This makes it increasingly difficult for users to pick the right version when providing APKs directly (early releases, uncensored downloads, itch.io, etc.).
I believe a single, multi-arch APK would simplify this.
The differing files amount to 7-8MB only per ABI AFAICS, making this reasonable size-wise.

**Comment by renpytom** [comment]
Compared to the 100 MB limit of Google Play, it's something like a 14% difference. I'd accept a patch that made it a choice between three apks or one big apk with all three architectures, but the three apks are the best a approach for Google Play, which is the main market for Android.

**Comment by Beuc** [comment]
OK, though isn't there a 2GB thing for Google-Play-only APKs?

**Comment by renpytom** [comment]
No, it's the opposite of that - while the APK format supports a 2GB limit, Google Play only distributes 100MB APKs, then makes you go through the Expansion APK mechanism to get the rest of your data.

**Comment by Beuc** [comment]
Yes that's what I meant.

**Comment by Beuc** [comment]
Ping? :)

**Comment by Beuc** [comment]
Any issue?

**Comment by renpytom** [comment]
Merged.
