### ISSUE TITLE
IOError: [Errno 2] No such file or directory:project.pr operties

### ISSUE THREAD

**Issue by decemer** [renpy/rapt#3]
Traceback (most recent call last):
  File "android.py", line 69, in <module>
    main()
  File "android.py", line 40, in main
    install_sdk.install_sdk(iface)
  File "buildlib\rapt\install_sdk.py", line 263, in install_sdk
    get_packages(interface)
  File "buildlib\rapt\install_sdk.py", line 186, in get_packages
    with open(plat.path("android-sdk/extras/google/play_apk_expansion/downloader
_library/project.properties"), "r") as f:
IOError: [Errno 2] No such file or directory: 'D:\renpy-6.99.8-sdk\rapt-master
\android-sdk-r23/extras/google/play_apk_expansion/downloader_library/project.pr
operties'

**Comment by renpytom** [comment]
Can you delete the android sdk directory and rerun installsdk, backing up the keyring file?

**Comment by decemer** [comment]
same result

**Comment by decemer** [comment]
i have done it,no use web download rapt-android,let it self download,and use android package downloader download android-r23 copy in to rapt file

**Comment by konistehrad** [comment]
This situation appears to be getting worse: Using the auto-installer, the SDK will install, but won't install the APK expansion extra. Even when it does, unfortunately, the APK expansion extra is now called `market_apk_expansion` not `play_apk_expansion`. Symlinking this into the right path will cause Renpy's auto SDK installer to complete, but "Configure," "Build Package," et al aren't eligible for interaction.

Recommend reopening this ticket for further eval.

**Comment by renpytom** [comment]
This is fixed in the current nightlies, but I haven't made a release yet.

**Comment by konistehrad** [comment]
@renpytom excellent I'll grab one of those, thanks for the prompt response!
