### ISSUE TITLE
Missing mixer.so in rapt.zip

### ISSUE THREAD

**Issue by telecoda** [renpy/rapt#4]
I am trying to use pygame on android with RAPT and it is working great.

However when I try to use pygame.mixer as per the instructions:
try:
    import pygame.mixer as mixer
except ImportError:
    import android.mixer as mixer

I am getting an error on Android.

NotImplementedError: Could not import pygame_sdl2.mixer: No module named mixer

I believe that the mixer.so library is missing from private/lib/python2.7/site_packages/pygame_sdl2.

**Comment by renpytom** [comment]
This should land in a nightly build sometime in the next day or so.
