### ISSUE TITLE
APP launch error: missing libpng16.so

### ISSUE THREAD

**Issue by ghost** [renpy/rapt#5]
Dear Sirs,
I have successfully packaged my game, created with renpy-6.99.11.1708.
I have used the latest RAPT source in this repo.
I have an error on my Android 5.1 complaining the missing libpng16.so shared library.
I have tested it also on Android Emulator.

> dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com....."],nativeLibraryDirectories=[/vernor/lib,/system/lib]]] couldn't find "libpng16.so"

Hi have used the common procedure with "android.py" to build the app.
I have no particular errors in build and configure logs.

What can i try?

Thank you

**Comment by ghost** [comment]
I checked _build_renpy.sh_ which builds native libraries (obviously needed).
I'm currently running the build with my Android NDK

**Comment by ghost** [comment]
I'm getting errors while building  "pygame_sdl2"
I have tried with the last commit on your repo and the latest release here https://github.com/renpy/pygame_sdl2/releases:

I get this error:

> ~/pygame_sdl2-renpy ~/rapt/native/build/armeabi
> pygame_sdl2.error is out of date.
> Traceback (most recent call last):
>   File "setup.py", line 97, in <module>
>     cython("pygame_sdl2.error", libs=sdl_libs)
>   File "/home/sunkiss/1_PRESENTE/pygame_sdl2-renpy/setuplib.py", line 245, in cython
>     c_fn])
>   File "/home/sunkiss/1_PRESENTE/rapt/native/install/armeabi/lib/python2.7/subprocess.py", line 506, in check_call
>     retcode = call(_popenargs, *_kwargs)
>   File "/home/sunkiss/1_PRESENTE/rapt/native/install/armeabi/lib/python2.7/subprocess.py", line 493, in call
>     return Popen(_popenargs, *_kwargs).wait()
>   File "/home/sunkiss/1_PRESENTE/rapt/native/install/armeabi/lib/python2.7/subprocess.py", line 679, in **init**
>     errread, errwrite)
>   File "/home/sunkiss/1_PRESENTE/rapt/native/install/armeabi/lib/python2.7/subprocess.py", line 1228, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

Do I have to "prepare" the pygame_sdl2 sources in some way?
The script is running is "native/scripts/pygame_sdl2.sh"

Thank you

**Comment by ghost** [comment]
done. i had to copy libs put in dist/libs also in ./libs

**Comment by DaveMcGr** [comment]
My phone has the same error as the Original Post. On my android device `libpng.so` can be found in `/system/lib64`, is it possible to use this library instead if `libpng16.so` or is there some way to include `libpng16.so` in the apk build?

Thanks

**Comment by mclaughlinconnor** [comment]
I can confirm. I was doing some messing about to try and get it to work and I found a rooted android phone where I created a copy of `libpng.so` in `/system/lib` named `libpng16.so`. Once I launched the app it had the exact same error with `libpng.so` replaced with `libSDL2.so`.
